#!/bin/sh 

case "$1" in 
    start)
    echo "Loading aesd char-device kernel module..."
    /etc/init.d/aesdchar_load
    ;;

    stop)
    echo "Unloading aesd char-device module..."
    /etc/init.d/aesdchar_unload
    ;;
    
    *)
    echo "Usage: $0 { start | stop }"
    exit 1
esac
exit 0